In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.datasets import load_digits

C:\Users\Vipin\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [2]:
dataset = load_digits()

In [3]:
X_train,X_test,y_train,y_test = train_test_split(dataset.data,dataset.target,test_size=0.3)

In [4]:
#Random Forest 
model_rf = RandomForestClassifier()
model_rf.fit(X_train,y_train)
model_rf.score(X_test,y_test)

0.9518518518518518

In [5]:
#Logistic Regression
model_lr = LogisticRegression()
model_lr.fit(X_train,y_train)
model_lr.score(X_test,y_test)

0.9611111111111111

In [6]:
#Support Vector Machine
model_svc = SVC()
model_svc.fit(X_train,y_train)
model_svc.score(X_test,y_test)

0.3925925925925926

In [7]:
from sklearn.model_selection import KFold

In [8]:
kf = KFold(n_splits=3)

In [9]:
# This is just to understand KFold
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [18]:
def getModel_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [19]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)
svc_list = []
randomF_list = []
logisticR_list = []
for train_index, test_index in folds.split(dataset.data,dataset.target):
    X_train, X_test, y_train, y_test = dataset.data[train_index], dataset.data[test_index], \
                                    dataset.target[train_index], dataset.target[test_index]
    svc_list.append(getModel_score(SVC(), X_train, X_test, y_train, y_test))
    randomF_list.append(getModel_score(RandomForestClassifier(),X_train,X_test,y_train,y_test))
    logisticR_list.append(getModel_score(LogisticRegression(),X_train,X_test,y_train,y_test))

In [20]:
svc_list

[0.39368770764119604, 0.41068447412353926, 0.4597315436241611]

In [21]:
randomF_list

[0.8903654485049833, 0.9131886477462438, 0.8859060402684564]

In [22]:
logisticR_list

[0.8953488372093024, 0.9499165275459098, 0.9093959731543624]

In [23]:
from sklearn.model_selection import cross_val_score

In [24]:
cross_val_score(LogisticRegression(),dataset.data,dataset.target,cv=3)

array([0.89534884, 0.94991653, 0.90939597])

In [25]:
cross_val_score(SVC(),dataset.data,dataset.target,cv=3)

array([0.39368771, 0.41068447, 0.45973154])

In [26]:
cross_val_score(RandomForestClassifier(),dataset.data,dataset.target,cv=3)

array([0.8820598 , 0.90984975, 0.89932886])

In [27]:
svm_score = cross_val_score(SVC(),dataset.data,dataset.target,cv=10)
np.average(svm_score)

0.48705191207774323

In [28]:
rf_score = cross_val_score(RandomForestClassifier(),dataset.data,dataset.target,cv=10)
np.average(rf_score)

0.916604422988985

In [29]:
logistic_score = cross_val_score(LogisticRegression(),dataset.data,dataset.target,cv=10)
np.average(logistic_score)

0.9310298346839012